### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dave181295** [Kuama-IT/android-document-scanner#10]
Device : Xiaomi redmi note 9

`E/PreviewView: The selected camera does not support the enabled use cases. Please disable use case and/or select a different camera. e.g. #setVideoCaptureEnabled(false)
    java.lang.IllegalStateException: The selected camera does not support the enabled use cases. Please disable use case and/or select a different camera. e.g. #setVideoCaptureEnabled(false)`

**Comment by giovanni-nic-kuama** [comment]
Seems like your device does not support CameraX Api. Since we added CameraX on version 0.1.5 you can try an earlier version and tweak it to your needs.  If you look [here](https://developer.android.com/training/camerax/devices) you should find an example app that shows if your device support the CameraX Api other than a list of supported devices.

Unfortunately we cannot avoid to use CameraX. The main problem was that based on the phone vendor, the output image was 'randomly' rotated (by 90deg, 180deg, or 270deg) and we didn't have a way to know which rotation the resulting frame would be for all devices. CameraX is the only API that address that issue, so we chose to move to this one.

**Comment by kuamanet** [comment]
We've haven't heard news in a while now, I'm closing this.  @Dave181295 feel free to re-open if needed!
